In [ ]:
import numpy as np
print(np.__version__)
import torch
print(torch.__version__)
import torch.nn.functional as F
import matplotlib.pylab as plt

1.21.6
1.12.0+cu113


# Pytorch Basics:


**Exercise #1:** Torch Tensors

**Your Task**: Convert the list to a tensor and check its properties.

*   the following list of integers <i>[0, 1, 2, 3, 4]</i> to a torch *int* tensor.
*   the following float list <i>[0.0, 1.0, 2.0, 3.0, 4.0]</i> to a torch *float* tensor.
*   Convert the torch int tensor to torch float tensor.



In [ ]:
# Convert a integer list with length 5 to a tensor
int_list = [1,2,3,4,5]
# YOUR CODE STARTS HERE
ints_to_tensor =torch.tensor( int_list,dtype=torch.int32)
#YOUR CODE ENDS HERE
print("The dtype of tensor object after converting it to tensor: ", ints_to_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", ints_to_tensor.type())
print("The size of the ints_to_tensor: ", ints_to_tensor.size())
print("The dimension of the ints_to_tensor: ",ints_to_tensor.ndimension())


The dtype of tensor object after converting it to tensor:  torch.int32
The type of tensor object after converting it to tensor:  torch.IntTensor
The size of the ints_to_tensor:  torch.Size([5])
The dimension of the ints_to_tensor:  1


In [ ]:
# Convert a float list with length 5 to a tensor
float_list = [0.0, 1.0, 2.0, 3.0, 4.0]
# YOUR CODE STARTS HERE
floats_to_tensor = torch.Tensor(float_list)
#YOUR CODE ENDS HERE

print("The dtype of tensor object after converting it to tensor: ", floats_to_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", floats_to_tensor.type())
print("The size of the floats_to_tensor: ", floats_to_tensor.size())
print("The dimension of the floats_to_tensor: ",floats_to_tensor.ndimension())

The dtype of tensor object after converting it to tensor:  torch.float32
The type of tensor object after converting it to tensor:  torch.FloatTensor
The size of the floats_to_tensor:  torch.Size([5])
The dimension of the floats_to_tensor:  1


In [ ]:
# Convert the integer tensor to float tensor
old_int_tensor = torch.tensor([0, 1, 2, 3, 4])
# YOUR CODE STARTS HERE
new_float_tensor = old_int_tensor.to(dtype=torch.float32)
#YOUR CODE ENDS HERE

print("The type of the new_float_tensor:", new_float_tensor.type())
print("The size of the new_float_tensor: ", new_float_tensor.size())
print("The dimension of the new_float_tensor: ",new_float_tensor.ndimension())

The type of the new_float_tensor: torch.FloatTensor
The size of the new_float_tensor:  torch.Size([5])
The dimension of the new_float_tensor:  1


**Exercise #2:** 2D Torch Tensors and 2D numpy arrays

**Your Task**: numpy vs. torch

*   Convert the given numpy array to a torch tensor; And torch tensor to a numpy array


In [ ]:
twoD_list = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
twoD_numpy = np.asarray(twoD_list)
print("The numpy array: ", twoD_numpy)
print("Type : ", twoD_numpy.dtype)

# Convert numpy array to tensor
# YOUR CODE STARTS HERE
twoD_tensor =torch.from_numpy(twoD_numpy)
#YOUR CODE ENDS HERE
print("\nNumpy Array -> Tensor:")
print("The tensor after converting:", twoD_tensor)
print("Type after converting: ", twoD_tensor.dtype)

# Convert torch tensor to numpy array
# YOUR CODE STARTS HERE
new_twoD_numpy =twoD_tensor.numpy()
#YOUR CODE ENDS HERE
print("\nTensor -> Numpy Array:")
print("The numpy array after converting: ", new_twoD_numpy)
print("Type after converting: ", new_twoD_numpy.dtype)


The numpy array:  [[11 12 13]
 [21 22 23]
 [31 32 33]]
Type :  int64

Numpy Array -> Tensor:
The tensor after converting: tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
Type after converting:  torch.int64

Tensor -> Numpy Array:
The numpy array after converting:  [[11 12 13]
 [21 22 23]
 [31 32 33]]
Type after converting:  int64


**Exercise #3:** 2D Torch Tensors and 2D numpy arrays

**Your Task**: Access the different elements of the tensor `twoD_tensor` and numpyarray `twoD_numpy`.



In [ ]:
# Slice rows 2nd and 3rd row
# YOUR CODE STARTS HERE
sliced_tensor = twoD_tensor [0 ,: ]
sliced_numpy = twoD_numpy[0,:]
# YOUR CODE STARTS HERE

print("Tensor: Result after tensor slicing ", sliced_tensor)
print("Tensor: Dimension after tensor slicing ", sliced_tensor.ndimension())
print("Numpy: Result after np slicing: ", sliced_numpy)
print("Numpy: Dimension after np slicing: ", sliced_numpy.ndim)

Tensor: Result after tensor slicing  tensor([11, 12, 13])
Tensor: Dimension after tensor slicing  1
Numpy: Result after np slicing:  [11 12 13]
Numpy: Dimension after np slicing:  1


<h2 id="Tensor_Op">Tensor Operations</h2>

**Exercise #4:** Dot Product

In this task, you will implement the dot product function for numpy arrays & torch tensors.

The dot product (also known as the scalar product or inner product) is the linear combination of the n real components of two vectors.

$$x \cdot y = x_1 y_1 + x_2 y_2 + \cdots + x_n y_n$$

**Your Task**: Implement the functions `NUMPY_dot` & `PYTORCH_dot`.

In [ ]:
def NUMPY_dot(x, y):
    """
    Dot product of two arrays.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.int64: scalar quantity.
    """
    # YOUR CODE STARTS HERE
    # for i in range(0,len(x)):
    #   x[i]=x[i]*y[i]

    # YOUR CODE ends HERE

    # return sum(x)
    return np.dot(x,y)        #np.asscalar is deprecated.Use item instead

In [ ]:
def PYTORCH_dot(x, y):
    """
    Dot product of two tensors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.int64: scalar quantity.
    """
    # YOUR CODE STARTS HERE
    # for i in range(0,len(x)):
    #   x[i]=x[i]*y[i]
    # YOUR CODE ends HERE

    return torch.dot(x,y)

In [ ]:
# TEST cases
X = np.asarray([1,2,3])
Y = np.asarray([4,-5,6])
print(f'NUMPY: Dot product of {X} and {Y} is {NUMPY_dot(X,Y)}')
print(type(NUMPY_dot(X,Y)),type(12))
assert NUMPY_dot(X,Y)==12

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print(f'Pytorch: Dot product of {X} and {Y} is {PYTORCH_dot(X,Y)}')
print(type(PYTORCH_dot(X,Y).item()),type(12))
assert PYTORCH_dot(X,Y).item()==12

NUMPY: Dot product of [1 2 3] and [ 4 -5  6] is 12
<class 'numpy.int64'> <class 'int'>
Pytorch: Dot product of tensor([1, 2, 3]) and tensor([ 4, -5,  6]) is 12
<class 'int'> <class 'int'>


**Exercise #5:** Outer Product

In this task, you will implement the outer product function for numpy arrays & torch tensors.

The outer product (also known as the tensor product) of vectors x and y is defined as

$$
x \otimes y =
\begin{bmatrix}
x_1 y_1 & x_1 y_2 & … & x_1 y_n\\
x_2 y_1 & x_2 y_2 & … & x_2 y_n\\
⋮ & ⋮ & ⋱ & ⋮ \\
x_m y_1 & x_m y_2 & … & x_m y_n
\end{bmatrix}
$$

**Your Task**: Implement the functions `NUMPY_outer` & `PYTORCH_outer`.

In [ ]:
def NUMPY_outer(x, y):
    """
    Compute the outer product of two vectors.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """
    # outer_product=np.zeros((len(x),len(y)),)
    # YOUR CODE STARTS HERE
    # for i in range(0,len(x)):
    #   for j in range(0,len(y)):
    #     outer_product[i][j]=np.multiply(x[i],y[j])


    # YOUR CODE ends HERE

    # return outer_product
    return np.outer(x,y)
    # return None


In [ ]:
def PYTORCH_outer(x, y):
    """
    Compute the outer product of two vectors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """
    # YOUR CODE STARTS HERE

    # YOUR CODE ends HERE

    return torch.outer(x,y)

In [ ]:
# TEST cases
X = np.asarray([1,2])
Y = np.asarray([1,3])
print(NUMPY_outer(X,Y))
print(f'NUMPY: Dot product of {X} and {Y} is \n{NUMPY_outer(X,Y)}')

x = np.array(['a', 'b', 'c'], dtype=object)
print(f'NUMPY: Dot product of {X} and {Y} is \n{NUMPY_outer(x, [1, 2, 3])}')

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print(f'Pytorch: Dot product of {X} and {Y} is \n{PYTORCH_outer(X,Y)}')

[[1 3]
 [2 6]]
NUMPY: Dot product of [1 2] and [1 3] is 
[[1 3]
 [2 6]]
NUMPY: Dot product of [1 2] and [1 3] is 
[['a' 'aa' 'aaa']
 ['b' 'bb' 'bbb']
 ['c' 'cc' 'ccc']]
Pytorch: Dot product of tensor([1, 2]) and tensor([1, 3]) is 
tensor([[1, 3],
        [2, 6]])


**Exercise #6:** Hadamard Product

In this task, you will implement the Hadamard product function, `multiply`, for numpy arrays & torch tensors.

The Hadamard product (also known as the Schur product or entrywise product) of vectors x and y is defined as

$$
x \circ y =
\begin{bmatrix}
x_{1} y_{1} & x_{2} y_{2} & … & x_{n} y_{n}
\end{bmatrix}
$$

**Your Task**: Implement the functions `NUMPY_multiply` & `PYTORCH_multiply`.

In [ ]:
def NUMPY_multiply(x, y):
    """
    Multiply arguments element-wise.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.
    y (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    numpy.ndarray: 1-dimensional numpy array.
    """
    # YOUR CODE STARTS HERE

    # YOUR CODE ends HERE

    return np.multiply(x,y)

In [ ]:
def PYTORCH_multiply(x, y):
    """
    Multiply arguments element-wise.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.Tensor: 1-dimensional torch tensor.
    """
    # YOUR CODE STARTS HERE

    # YOUR CODE ends HERE

    return torch.multiply(x,y)

In [ ]:
# TEST cases
X = np.asarray([1,2,3])
Y = np.asarray([4,-5,6])
print(f'NUMPY: Dot product of {X} and {Y} is {NUMPY_multiply(X,Y)}')

X = torch.from_numpy(X)
Y = torch.from_numpy(Y)
print(f'Pytorch: Dot product of {X} and {Y} is {PYTORCH_multiply(X,Y)}')

NUMPY: Dot product of [1 2 3] and [ 4 -5  6] is [  4 -10  18]
Pytorch: Dot product of tensor([1, 2, 3]) and tensor([ 4, -5,  6]) is tensor([  4, -10,  18])


**Exercise #7:** ReLU

In this task, you will implement the ReLU activation function for numpy arrays and torch tensors.

The ReLU activation (also known as the rectifier or rectified linear unit) matrix Z resulting from applying the ReLU function to matrix X is defined such that for $X,Z \in M_{m \times n} (\mathbb{R})$,

$$Z = {\tt ReLU}(X) \implies \begin{cases}z_{ij} = x_{ij}&{\mbox{if }}x_{ij}>0\\z_{ij} = 0&{\mbox{otherwise.}}\end{cases}$$

For reference, it is common to use the notation $X = (x_{ij})$ and $Z = (z_{ij})$.

**Your Task:** Implement the functions `NUMPY_ReLU` & `PYTORCH_ReLU`.

In [ ]:
def NUMPY_ReLU(x):
    """
    Applies the rectified linear unit function element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional numpy array.

    Returns:
    numpy.ndarray: 2-dimensional numpy array.
    """
    z=np.zeros(x.shape)
    relu_lambda =lambda x : x if x>0 else 0
    # YOUR CODE STARTS HERE
    for i in range(0,len(z[0])):
       for j in range(0,len(z[1])):
         z[i][j]=relu_lambda(x[i][j])
    # YOUR CODE ends HERE

    return z

In [ ]:
def PYTORCH_ReLU(x):
    """
    Applies the rectified linear unit function element-wise.

    Parameters:
    x (torch.Tensor): 2-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """
    # YOUR CODE STARTS HERE
    # z=torch.zeros(x.shape)
    # for i in range(0,len(x)):
    #    for j in range(0,len(y)):
    #      z[i][j]=(x[i][j])
    # YOUR CODE ends HERE

    return torch.nn.ReLU(x)

In [ ]:
#Test Cases
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3,3))
print(NUMPY_ReLU(X))

X = torch.from_numpy(X)
print(PYTORCH_ReLU(X))

[[  0.   0. 653.]
 [216.   0.   0.]
 [731. 383.  33.]]


RuntimeError: ignored

# Pytorch Differentiation

**Exercise #8:**

**Your Task**: Determine the derivative of $ y = 2x^3+x $ at $x=1$

In [ ]:
# YOUR CODE STARTS HERE
x= torch.tensor(1.0, requires_grad = True)
y=(2*(x**3)+x)
print(y)
y.backward()
# YOUR CODE ends HERE
print('the graid of y wrt x at x = 1 is ',x.grad)
assert x.grad.item()==7

tensor(3., grad_fn=<AddBackward0>)
the graid of y wrt x at x = 1 is  tensor(7.)


**Exercise #9:**

**Your Task**: Determine the <b>partial derivative</b> of the function: $f(u,v)=vu+u^{2}$ at $(u,v)=(1,2)$

*   with respect to u
*   with respect to v



In [ ]:
# YOUR CODE STARTS HERE

# Calculate f(u, v) = v * u + u^2 at u = 1, v = 2
u = torch.tensor(1.0, requires_grad = True)
v = torch.tensor(2.0, requires_grad = True)
f = (u*v)+(u**2)
f.backward()
print("The result of v * u + u^2: ", f)

# Calculate the derivative with respect to u

print("The partial derivative with respect to u: ", u.grad)

# Calculate the derivative with respect to v
print("The partial derivative with respect to u: ", v.grad)
# YOUR CODE ENDS HERE


The result of v * u + u^2:  tensor(3., grad_fn=<AddBackward0>)
The partial derivative with respect to u:  tensor(4.)
The partial derivative with respect to u:  tensor(1.)


**Exercise #10:**

**Your Task**: Visualize the relu activation function and it derivative



In [ ]:
x = torch.linspace(-3, 3, 100, requires_grad = True)
# Take the derivative of Relu with respect to multiple value in x.
Y = torch.nn.ReLU(x)
print(Y)
Y.backward()

# Plot out the function and its derivative
plt.plot(x.detach().numpy(), Y.detach().numpy(), label = 'ReLU function')
plt.plot(x.detach().numpy(), x.grad.numpy(), label = 'ReLU derivative')
plt.xlabel('x')
plt.legend()
plt.show()

RuntimeError: ignored