In [ ]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

1.21.6


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [ ]:
# YOUR CODE STARTS HERE
arr =np.full((2, 3), 5)
# YOUR CODE ENDS HERE
print(arr)

[[5 5 5]
 [5 5 5]]


**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [ ]:
# YOUR CODE STARTS HERE
rand_arr =np.random.rand(2,3)
# YOUR CODE ENDS HERE
print(rand_arr)

[[0.48497553 0.69420432 0.89032313]
 [0.89371611 0.56878036 0.30121624]]


In [ ]:
#YOUR CODE STARTS HERE
arr_sum = sum(map(sum, rand_arr))
# arr_mean =sum(rand_arr)/sum(map(len, rand_arr))
arr_mean =sum(map(sum, rand_arr))/sum(map(len, rand_arr))
arr_max = max(map(max, rand_arr))
arr_min = min(map(min, rand_arr))
#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')

sum: 3.833215680156096
mean: 0.638869280026016
max: 0.8937161079451426
min:0.3012162377308565


In [ ]:
list(map(max, rand_arr))

[0.8663916116707746, 0.8032331291826542]

In [ ]:
# sum(map(len, rand_arr))
# rand_arr[:,0:2]
# rand_arr[1,:]
print(list(map(max,rand_arr[1,:])))

In [ ]:
# rand_arr[np.where(rand_arr==arr_min)]
np.where(rand_arr==arr_min)

(array([1]), array([2]))

**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value

**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [ ]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')
arr_transpose=np.transpose(arr)
print(f'Array:\n{arr_transpose}\n')
# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
max_idx = np.where(arr==max(map(max, arr)))
min_idx = np.where(arr==min(map(min, arr)))
print(max_idx,min_idx)
# print(list(map(min, arr)))
#Find the indices of maximum and minimum value along each of its columns.
max_list=list(map(max, arr_transpose))
min_list=list(map(min, arr_transpose))
print(max_list)
max_col=[]
min_col=[]
for element in max_list:
  max_col.append(list(np.where (arr_transpose==element)))
for element in min_list:
  min_col.append(list(np.where(arr_transpose== element)))
print(f'max col :\n{max_col}\n')
print(f'min col :\n{min_col}\n')

#Find the indices of maximum and minimum value along each of the its rows.
max_list=list(map(max, arr))
min_list=list(map(min, arr))
max_row=[]
min_row=[]
for element in max_list:
  max_row.append(list(np.where (arr==element)))
for element in min_list:
  min_row.append(list(np.where(arr== element)))
print(f'max row :\n{max_row}\n')
print(f'min row :\n{min_row}\n')
#YOUR CODE ENDS HERE

Array:
[[ 5 12 51 25]
 [25 29  2 27]]

Array:
[[ 5 25]
 [12 29]
 [51  2]
 [25 27]]

(array([0]), array([2])) (array([1]), array([2]))
[25, 29, 51, 27]
max col :
[[array([0, 3]), array([1, 0])], [array([1]), array([1])], [array([2]), array([0])], [array([3]), array([1])]]

min col :
[[array([0]), array([0])], [array([1]), array([0])], [array([2]), array([1])], [array([0, 3]), array([1, 0])]]

max row :
[[array([0]), array([2])], [array([1]), array([1])]]

min row :
[[array([0]), array([0])], [array([1]), array([2])]]

